export const WALKING_ACHIEVEMENTS = [
  {
    id: 'first-goal',
    category: 'goal',
    seriesId: 'goal-count',
    tier: 1,
    sortOrder: 10,
    enabled: true,
    visibility: 'public',
    icon: '🌱',
    title: '첫 걸음',
    description: '하루 걸음 목표를 처음 달성해요.',
    condition: {
      type: 'metricThreshold',
      metric: 'goalCompletionCount',
      operator: 'gte',
      target: 1,
    },
    rewards: [{ type: 'coin', amount: 5 }],
  },
  {
    id: 'goal-three',
    category: 'goal',
    seriesId: 'goal-count',
    tier: 2,
    sortOrder: 20,
    enabled: true,
    visibility: 'public',
    icon: '👟',
    title: '작심삼일',
    description: '하루 걸음 목표를 3회 달성해요.',
    condition: {
      type: 'metricThreshold',
      metric: 'goalCompletionCount',
      operator: 'gte',
      target: 3,
    },
    rewards: [{ type: 'coin', amount: 10 }],
  },
  {
    id: 'ten-thousand',
    category: 'steps',
    seriesId: 'daily-steps',
    tier: 1,
    sortOrder: 30,
    enabled: true,
    visibility: 'public',
    icon: '✨',
    title: '1만 클럽',
    description: '하루에 10,000보 이상 걸어요.',
    condition: {
      type: 'metricThreshold',
      metric: 'maxDailySteps',
      operator: 'gte',
      target: 10000,
    },
    rewards: [{ type: 'coin', amount: 10 }],
  },
  {
    id: 'goal-seven',
    category: 'goal',
    seriesId: 'goal-count',
    tier: 3,
    sortOrder: 40,
    enabled: true,
    visibility: 'public',
    icon: '🏅',
    title: '달성 습관',
    description: '하루 걸음 목표를 7회 달성해요.',
    condition: {
      type: 'metricThreshold',
      metric: 'goalCompletionCount',
      operator: 'gte',
      target: 7,
    },
    rewards: [{ type: 'coin', amount: 20 }],
  },
  {
    id: 'twenty-thousand',
    category: 'steps',
    seriesId: 'daily-steps',
    tier: 2,
    sortOrder: 50,
    enabled: true,
    visibility: 'public',
    icon: '🔥',
    title: '불타는 발',
    description: '하루에 20,000보 이상 걸어요.',
    condition: {
      type: 'metricThreshold',
      metric: 'maxDailySteps',
      operator: 'gte',
      target: 20000,
    },
    rewards: [{ type: 'coin', amount: 15 }],
  },
  {
    id: 'goal-thirty',
    category: 'goal',
    seriesId: 'goal-count',
    tier: 4,
    sortOrder: 60,
    enabled: true,
    visibility: 'public',
    icon: '🏆',
    title: '꾸준좌',
    description: '하루 걸음 목표를 30회 달성해요.',
    condition: {
      type: 'metricThreshold',
      metric: 'goalCompletionCount',
      operator: 'gte',
      target: 30,
    },
    rewards: [{ type: 'coin', amount: 50 }],
  },
];
